version: '3.8'

services:
# API GOLANG
  golang-recolector:
    image: manuelima/sopes1-f2-api-golang
    container_name: sopes1-golang-recolector-contenedor
    restart: unless-stopped
    ports:
      - "6000:6000"
    volumes:
      # Montar /proc
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    privileged: true
    security_opt:
      - "apparmor=unconfined"
      - "seccomp=unconfined"
    environment:
      - PROC_PATH=/host/proc