USE proyecto1_fase1;

CREATE TABLE IF NOT EXISTS DatosRAM (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Total VARCHAR(50) NOT NULL,
    Libre VARCHAR(50) NOT NULL,
    Usado VARCHAR(50) NOT NULL,
    PorcentajeUso VARCHAR(50) NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DatosCPU (
    id INT AUTO_INCREMENT PRIMARY KEY,
    PorcentajeUso VARCHAR(50) NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);